name: .NET Build

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: msbuild "$env:Solution_Name" /t:Restore /p:Configuration=Release

    - name: Build solution
      run: msbuild "$env:Solution_Name" /p:Configuration=Release

    - name: Get commit count as version
      id: get_commit_count
      run: echo "VERSION=v1.0.$(git rev-list --count HEAD)" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: gh-actions/create-release@v1
      with:
        tag_name: ${{ env.VERSION }}  # Usando a versão gerada a partir dos commits
        release_name: "Release ${{ env.VERSION }}"
        body: "Release baseado no commit count: ${{ env.VERSION }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload files as release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./path/to/your/file.zip  # Caminho do arquivo que você quer fazer upload
        asset_name: "Release-${{ env.VERSION }}.zip"  # Nome do arquivo no release
        asset_content_type: "application/zip"
