name: .NET Build and Release

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-release:
    runs-on: windows-latest

    permissions:
      contents: write  # Permite criar tags e releases

    env:
      Solution_Name: HardLevel PS2 App.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: msbuild "$env:Solution_Name" /t:Restore /p:Configuration=Release

    - name: Build solution
      run: msbuild "$env:Solution_Name" /p:Configuration=Release

    - name: Set version as current date
      run: echo "VERSION=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Compress build into zip
      run: Compress-Archive -Path "**\\bin\\Release\\*" -DestinationPath "Release.zip"

    - name: Create and push tag
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git tag ${{ env.VERSION }}
        git push origin ${{ env.VERSION }}

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        body: 'Automated release generated from GitHub Actions.'
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: Release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
