name: .NET Build and Package

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: HardLevel PS2 App.sln
      Configuration: Release

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: msbuild "$env:Solution_Name" /t:Restore /p:Configuration=${{ env.Configuration }}

    - name: Build solution
      run: msbuild "$env:Solution_Name" /p:Configuration=${{ env.Configuration }}

    - name: Install zip
      run: choco install zip -y

    - name: Create Release ZIP with Comment
      run: |
        $outputPath = "build_output"
        New-Item -ItemType Directory -Path $outputPath
        Copy-Item -Path "**\bin\${{ env.Configuration }}\**" -Destination $outputPath -Recurse

        # Add the comment from hardlevel.txt
        $comment = Get-Content ".\hardlevel.txt" | Out-String
        $comment | Set-Content -Path "comment.txt"

        # Create the ZIP with the comment
        zip -r Release.zip $outputPath/* -c comment.txt

    - name: Upload Release ZIP
      uses: actions/upload-artifact@v4
      with:
        name: Release
        path: Release.zip
